### ISSUE TITLE
problem with set root password

### ISSUE THREAD

**Issue by rfakit** [virt-lightning/esxi-cloud-images#4]
I Created esxi image via the https://github.com/virt-lightning/esxi-cloud-images project. I imported it to Openstack.
but i have problem to set password for root user.
how can i set password for root?
what is the default username to connect via ssh through ssh-key added by Openstack

**Comment by goneri** [comment]
Hi!

Sorry for the long delay, I totally missed the notification. The final image is a "Cloud Image" and as such, it has no default password. It instead loads the SSH key from the metadata of the cloud environment.
This being said, you can adjust the script to set a password,
See: https://github.com/virt-lightning/esxi-cloud-images/blob/master/build.sh#L39-L41
